# Generated by Django 2.2.3 on 2019-12-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190925_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='aid',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
